// Define the candy type
const candyTypeList = [
  "Chocolate",
  "Gummy",
  "Hard candy",
  "Toffee",
  "Lollipop",
  "Jelly",
  "Chewy",
  "Bubble",
  "Fudge",
  "Caramel",
  "Fruit Chews",
  "Sour Candy",
  "Chocolate Bar",
  "Fruit Snacks",
  "Coconut Candy",
  "Nougat",
  "Marshmallow",
  "Licorice",
  "Peanut Butter",
  "Cotton Candy",
  "Candy Corn",
  "Peanut Brittle",
  "Rock Candy",
  "Taffy",
  "Jelly Beans",
  "Gumdrops",
  "Mint Candy",
  "Candy Canes",
  "Smarties",
  "M&Ms",
  "Kit-Kat",
  "Snickers",
  "Twix",
  "Reese's",
  "Skittles",
  "Starburst",
  "Jolly Ranchers",
  "Hershey's",
  "Milky Way",
  "3 Musketeers",
  "Butterfinger",
  "Almond Joy",
  "Twizzlers",
  "Sour Patch Kids",
  "Milk Duds",
  "Tootsie Rolls",
  "Blow Pops",
  "Dum Dums",
  "Tootsie Pops",
];
module.exports = candyTypeList;
